//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Taller_AdminShop.Classes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int id_usuario { get; set; }
        public string contraseña { get; set; }
        public int tipo_usuario { get; set; }
        public string correo { get; set; }
        public Nullable<int> dni { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public Nullable<int> telefono { get; set; }
        public string instagram { get; set; }
    }
}
